kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jira-shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem

