apiVersion: v1
kind: Secret
metadata:
  name: rh1-osdcluster-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWd4SzI5elpHTnNkWE4wWlhJNlN6UkNRVGhFUzFoR09VSTBNMWxNT1RrelRUbFNNRlpCTUVSRFdrUTBXRmhSVWpRNFFsSXhXVGRFUWpOS05sWlZRVFpNTkVFeFIxYzRWekJKTkVrM1FRPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson